RESTORAUNTS = [
    {
        'id': 1,
        'name': 'Гриль Хаус',
    },
    {
        'id': 2,
        'name': 'Дом Культур',
    },
    {
        'id': 3,
        'name': 'Квели',
    },
    {
        'id': 4,
        'name': 'Люди как люди',
    },
    {
        'id': 5,
        'name': 'Take IT Easy',
    },
]

MENU = [
    {
        'id': 1,
        'restoraunt_id': 1,
        'name': 'Куриная грудка',
        'price': 320,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Гриль%20Хаус/Куриная грудка — 320 руб.jpeg',
    },
    {
        'id': 2,
        'restoraunt_id': 1,
        'name': 'Луковые кольца',
        'price': 140,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Гриль%20Хаус/Луковые кульца — 140 руб.jpeg',
    },
    {
        'id': 3,
        'restoraunt_id': 1,
        'name': 'Салат Цезарь с курицей',
        'price': 320,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Гриль%20Хаус/Салат Цезарь с курицей — 320 руб.jpeg',
    },
    {
        'id': 4,
        'restoraunt_id': 1,
        'name': 'Стейк лосося',
        'price': 710,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Гриль%20Хаус/Стейк лосося — 710 руб.jpeg',
    },
    {
        'id': 5,
        'restoraunt_id': 1,
        'name': 'Шаурма с курицей',
        'price': 200,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Гриль%20Хаус/Шаурма с курицей — 200 руб.jpeg',
    },

    {
        'id': 6,
        'restoraunt_id': 2,
        'name': 'Люля из говядины',
        'price': 370,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Дом Культур/Люля из говядины — 370 руб.jpeg',
    },
    {
        'id': 7,
        'restoraunt_id': 2,
        'name': 'Мидии в сливочном соусе',
        'price': 780,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Дом Культур/Мидии в сливочном соусе — 780 руб.jpeg',
    },
    {
        'id': 8,
        'restoraunt_id': 2,
        'name': 'Паста с креветками и оливками',
        'price': 590,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Дом Культур/Паста с креветками и оливками — 590 руб .jpeg',
    },
    {
        'id': 9,
        'restoraunt_id': 2,
        'name': 'Свиная рулька с мини картофелем',
        'price': 790,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Дом Культур/Свиная рулька с мини картофелем — 790 руб.jpeg',
    },
    {
        'id': 10,
        'restoraunt_id': 2,
        'name': 'Чахохбили',
        'price': 460,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Дом Культур/Чахохбили — 460 руб.jpeg',
    },

    {
        'id': 11,
        'restoraunt_id': 3,
        'name': 'Дорадо',
        'price': 1116,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Квели/Дорадо — 1116 руб.jpeg',
    },
    {
        'id': 12,
        'restoraunt_id': 3,
        'name': 'Сациви с курицей',
        'price': 552,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Квели/Сациви с курицей — 552 руб.jpeg',
    },
    {
        'id': 13,
        'restoraunt_id': 3,
        'name': 'Скумбрия на углях',
        'price': 480,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Квели/Скумбрия на углях — 480 руб.jpeg',
    },
    {
        'id': 14,
        'restoraunt_id': 3,
        'name': 'Стейк из лосося',
        'price': 1156,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Квели/Стейк из лосося — 1156 руб.jpeg',
    },
    {
        'id': 15,
        'restoraunt_id': 3,
        'name': 'Шашлык из индейки',
        'price': 552,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Квели/Шашлык из индейки — 552 руб.jpeg',
    },

    {
        'id': 16,
        'restoraunt_id': 4,
        'name': 'Американский завтрак',
        'price': 360,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Люди как люди/Американский завтрак — 360 руб.jpeg',
    },
    {
        'id': 17,
        'restoraunt_id': 4,
        'name': 'Бургер с мраморной говядиной',
        'price': 530,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Люди как люди/Бургер с мраморной говядиной — 530 руб.jpeg',
    },
    {
        'id': 18,
        'restoraunt_id': 4,
        'name': 'Глазунья с лососем',
        'price': 450,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Люди как люди/Глазунья с лососем — 450 руб.jpeg',
    },
    {
        'id': 19,
        'restoraunt_id': 4,
        'name': 'Креветки темпура с соусом кимчи',
        'price': 690,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Люди как люди/Креветки темпура с соусом кимчи — 690 руб.jpeg',
    },
    {
        'id': 20,
        'restoraunt_id': 4,
        'name': 'Пицца 4 сыра с песто',
        'price': 790,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Люди как люди/Пицца 4 сыра с песто — 790 руб.jpeg',
    },

    {
        'id': 21,
        'restoraunt_id': 5,
        'name': 'Гренки чесночные',
        'price': 130,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Take IT Easy/Гренки чесночные — 130 руб.jpeg',
    },
    {
        'id': 22,
        'restoraunt_id': 5,
        'name': 'Картофель фри',
        'price': 150,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Take IT Easy/Картофель фри — 150 руб.jpeg',
    },
    {
        'id': 23,
        'restoraunt_id': 5,
        'name': 'Куриный шашлык',
        'price': 330,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Take IT Easy/Куриный шашлык — 330 руб.jpeg',
    },
    {
        'id': 24,
        'restoraunt_id': 5,
        'name': 'Ролл Калифорния',
        'price': 350,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Take IT Easy/Ролл Калифорния — 350 руб.jpeg',
    },
    {
        'id': 25,
        'restoraunt_id': 5,
        'name': 'Ролл Филадельфия',
        'price': 480,
        'picture_url': 'https://cdn-user14927.skyeng.ru/tg-bot/lmsh/restoraunts/Take IT Easy/Ролл Филадельфия — 480 руб.jpeg',
    },
]
